.PHONY: all
all: audit-log-reference.html clone-plugin-options-variables.html connection-control-variables.html innodb-parameters.html keyring-system-variables.html mysql-cluster-options-variables.html performance-schema-system-variables.html pluggable-authentication-system-variables.html replication-options-binary-log.html replication-options-gtids.html replication-options-reference.html replication-options-replica.html replication-options-source.html replication-options.html server-system-variables.html validate-password-options-variables.html x-plugin-options-system-variables.html server-administration.html

audit-log-reference.html:
	wget https://dev.mysql.com/doc/refman/8.0/en/audit-log-reference.html -O $@
clone-plugin-options-variables.html:
	wget https://dev.mysql.com/doc/refman/8.0/en/clone-plugin-options-variables.html -O $@
connection-control-variables.html:
	wget https://dev.mysql.com/doc/refman/8.0/en/connection-control-variables.html -O $@
innodb-parameters.html:
	wget https://dev.mysql.com/doc/refman/8.0/en/innodb-parameters.html -O $@
keyring-system-variables.html:
	wget https://dev.mysql.com/doc/refman/8.0/en/keyring-system-variables.html -O $@
mysql-cluster-options-variables.html:
	wget https://dev.mysql.com/doc/refman/8.0/en/mysql-cluster-options-variables.html -O $@
performance-schema-system-variables.html:
	wget https://dev.mysql.com/doc/refman/8.0/en/performance-schema-system-variables.html -O $@
pluggable-authentication-system-variables.html:
	wget https://dev.mysql.com/doc/refman/8.0/en/pluggable-authentication-system-variables.html -O $@
replication-options-binary-log.html:
	wget https://dev.mysql.com/doc/refman/8.0/en/replication-options-binary-log.html -O $@
replication-options-gtids.html:
	wget https://dev.mysql.com/doc/refman/8.0/en/replication-options-gtids.html -O $@
replication-options-reference.html:
	wget https://dev.mysql.com/doc/refman/8.0/en/replication-options-reference.html -O $@
replication-options-replica.html:
	wget https://dev.mysql.com/doc/refman/8.0/en/replication-options-replica.html -O $@
replication-options-source.html:
	wget https://dev.mysql.com/doc/refman/8.0/en/replication-options-source.html -O $@
replication-options.html:
	wget https://dev.mysql.com/doc/refman/8.0/en/replication-options.html -O $@
server-system-variables.html:
	wget https://dev.mysql.com/doc/refman/8.0/en/server-system-variables.html -O $@
validate-password-options-variables.html:
	wget https://dev.mysql.com/doc/refman/8.0/en/validate-password-options-variables.html -O $@
x-plugin-options-system-variables.html:
	wget https://dev.mysql.com/doc/refman/8.0/en/x-plugin-options-system-variables.html -O $@
server-administration.html:
	wget https://dev.mysql.com/doc/translation-refman/8.0/en/server-administration.html -O $@
